# Generated by Django 5.1 on 2025-10-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration for the accounts app.
    
    Creates the Account model with fields for managing both patients and psychologists.
    Includes indexes for optimizing queries by role, email, and combined role+email lookups.
    
    Fields:
    - name: First name of the account holder (max 100 chars)
    - last_name: Last name of the account holder (max 100 chars)
    - age: Age as positive integer
    - gender: Choice field (M/F/O)
    - phone: Phone number (max 20 chars)
    - email: Unique email address for account identification
    - role: User role (patient or psychologist)
    - created_at: Timestamp of account creation
    - updated_at: Timestamp of last update
    
    Indexes:
    - Composite index on (role, email) for filtering by role and email
    - Single index on email for email lookups
    
    Ordering:
    - Default ordering by last_name, then name
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('psychologist', 'Psychologist')], max_length=20, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['last_name', 'name'],
                'indexes': [models.Index(fields=['role', 'email'], name='accounts_ac_role_026657_idx'), models.Index(fields=['email'], name='accounts_ac_email_b00920_idx')],
            },
        ),
    ]
