# Generated by Django 5.1 on 2025-11-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('psychologist', 'Psychologist'), ('supervisor', 'Supervisor')], max_length=20, verbose_name='Role'),
        ),
    ]
