# Generated by Django 5.1 on 2025-10-13 21:22

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):
    """Initial migration for the polls app.
    
    Creates the Poll model with fields.
    
    Fields:
    - description: Description of the poll (max 255 chars)
    - rate: decimal number between 0 and 5
    - created_at: Timestamp of poll creation
    - updated_at: Timestamp of last update
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('rate', models.DecimalField(max_digits=3, decimal_places=1, verbose_name='Rate', validators=[MinValueValidator(0), MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
    ]
