# Generated by Django 5.1 on 2025-10-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration for the appointments app.
    
    Creates the Appointment model for managing appointment scheduling between
    patients and psychologists.
    
    Fields:
    - date: Date of the appointment
    - time: Time of the appointment
    - status: Current status (scheduled/confirmed/completed/cancelled/no_show)
    - created_at: Timestamp of appointment creation
    - updated_at: Timestamp of last update
    - patient: Foreign key to Account with role='patient'
    - psychologist: Foreign key to Account with role='psychologist'
    
    Constraints:
    - unique_together on (psychologist, date, time) prevents double-booking
    
    Indexes:
    - Composite index on (date, psychologist) for scheduling queries
    - Composite index on (patient, status) for patient appointment lookups
    
    Ordering:
    - Default ordering by date and time (descending)
    """

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Appointment Date')),
                ('time', models.TimeField(verbose_name='Appointment Time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='accounts.account', verbose_name='Patient')),
                ('psychologist', models.ForeignKey(limit_choices_to={'role': 'psychologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_appointments', to='accounts.account', verbose_name='Psychologist')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date', 'psychologist'], name='appointment_date_98dace_idx'), models.Index(fields=['patient', 'status'], name='appointment_patient_44acdc_idx')],
                # Validate if the appointment is not double-booked
                'unique_together': {('psychologist', 'date', 'time')},
            },
        ),
    ]
