# Generated by Django 5.1 on 2025-10-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration for the offices app.
    
    Creates the DoctorsOffice model for managing doctor's office locations.
    
    Fields:
    - name: Office name (max 200 chars)
    - address: Full office address as text
    - phone: Phone number (max 20 chars)
    - email: Email address for office contact
    - created_at: Timestamp of office creation
    - updated_at: Timestamp of last update
    - psychologist: Optional foreign key to Account with role='psychologist'
    
    Relationships:
    - Many-to-one with Account (psychologist role only, nullable)
    - SET_NULL on delete to preserve office data if psychologist is removed
    
    Ordering:
    - Default ordering by office name
    """

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Office Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('psychologist', models.ForeignKey(blank=True, limit_choices_to={'role': 'psychologist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_offices', to='accounts.account', verbose_name='Managing Psychologist')),
            ],
            options={
                'verbose_name': "Doctor's Office",
                'verbose_name_plural': "Doctors' Offices",
                'ordering': ['name'],
            },
        ),
    ]
