# Generated by Django 5.1 on 2025-10-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration for the doctors app.
    
    Creates the Doctor model for linking psychologists to offices with specialties.
    
    Fields:
    - specialty: Choice field for psychology specializations (clinical/cognitive/developmental/social/neuropsychology/counseling)
    - created_at: Timestamp of doctor profile creation
    - updated_at: Timestamp of last update
    - account: OneToOneField to Account with role='psychologist'
    - doctors_office: Foreign key to DoctorsOffice
    
    Relationships:
    - One-to-one with Account (psychologist role only)
    - Many-to-one with DoctorsOffice
    
    Ordering:
    - Default ordering by account's last_name, then name
    """

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('clinical', 'Clinical Psychology'), ('cognitive', 'Cognitive Psychology'), ('developmental', 'Developmental Psychology'), ('social', 'Social Psychology'), ('neuropsychology', 'Neuropsychology'), ('counseling', 'Counseling Psychology')], max_length=50, verbose_name='Specialty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('account', models.OneToOneField(limit_choices_to={'role': 'psychologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='accounts.account', verbose_name='Psychologist Account')),
                ('doctors_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='offices.doctorsoffice', verbose_name="Doctor's Office")),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['account__last_name', 'account__name'],
            },
        ),
    ]
